---
title: "Simple document"
output: github_document
---

```{r setup, echo = FALSE, message = FALSE}
library(tidyverse)
library(readxl)
library(haven)
```

Let's import the `FAS_litters.csv` csv.

```{r}
litters_df = 
  read_csv("data/FAS_litters.csv")

# convert space " " in the column names to "_"
# using func ”clean_names()“ from pkg "janitor”
litters_df =
  janitor::clean_names(litters_df) 


```

absolute path

```{r}
litters_df_abs = 
  read_csv("/Users/10507/Desktop/Courses/Data Science I/课程记录/L5/lecture5_data_import/data/FAS_litters.csv")

litters_df_abs = 
  janitor::clean_names(litters_df_abs) 

```

Import the `FAS_pups.csv` dataset Using both absolute and relative paths.

```{r}
pups_df =
  read_csv("data/FAS_pups.csv")
pups_df =
  janitor::clean_names(pups_df)

pups_df_abs =
  read_csv("/Users/10507/Desktop/Courses/Data Science I/课程记录/L5/lecture5_data_import/data/FAS_pups.csv")
pups_df_abs =
  janitor::clean_names(pups_df_abs)
```

## Look at data

```{r}
litters_df

head(litters_df)
```

You can use `view`

```{r, eval = FALSE}
view(litters_df)
```

Look at a data summary

```{r}
str(litters_df)

skimr::skim(litters_df)
```

## Options in read_*

```{r}
litters_df = 
  read_csv(
    "data/FAS_litters.csv",
    skip = 10, col_names = FALSE # skip 10 rows
    ) 
```

Look at NA values

```{r}
litters_df = 
  read_csv(
    "data/FAS_litters.csv",
    na = c("NA", 19) # treat "NA" and 19 as missing data
    ) 
```

Column types

```{r}
litters_df = 
  read_csv(
    "data/FAS_litters.csv", 
    col_types = 
      cols(
        Group = col_character()
      )
    ) 
```

## Other file types

Import a __xlsx__ file first.

```{r}
mlb_df = 
  read_excel("data/mlb11.xlsx")
```

Import a __SAS__ file.

```{r}
pulse_df = 
  read_sas("data/public_pulse_data.sas7bdat")

```

## Base R

DON'T do this:

```{r, eval = FALSE}
litters_df = 
  read.csv("data/FAS_litters.csv") 
# NEVER use this! Use read_csv() instead.

litters_df$Group
# DONT use $ either.
```

## Export data

```{r}
litters_df_clean = 
  read_csv("data/FAS_litters.csv")
litters_df_clean = 
  janitor::clean_names(litters_df_clean)

write_csv(litters_df_clean, "data/litters_clean.csv")
# write data to the file "data/litters_clean.csv"
```



